### ISSUE TITLE
tableau url having # dont open using the  complete path

### ISSUE THREAD

**Issue by kolhead** [ds2co/react-tableau-report#2]
We are facing a issue using this project to render a tableau url 
For example if we have a URL as below

http://abc.com/#/a/b/c

The react-tableau-report only opens till  http://abc.com/.

We found the issue in this part of code 
https://github.com/ds2co/react-tableau-report/blob/master/src/TableauReport.js#L73

Here it reads only parsed.host , now if a URL has a # in between then it only picks up the url path before the #  
to fix it I think we need this
let result = parsed.protocol + '//' + parsed.host + '/' + parsed.hash;

Can you please check this issue and let us know

**Comment by c-bryant** [comment]
Fix in PR #3
